version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6.12
    environment:
      CONTRACTS_COMMIT_HASH: '78fe8dd'
    steps:
      - checkout
      - run: echo 'export PATH=$HOME/CIRCLE_PROJECT_REPONAME/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: yarn
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
      - run: wget https://s3.amazonaws.com/testrpc-shapshots/${CONTRACTS_COMMIT_HASH}.zip
      - run: unzip ${CONTRACTS_COMMIT_HASH}.zip -d testrpc_snapshot
      - run: node ./node_modules/lerna/bin/lerna.js bootstrap
      - run: yarn lerna:run bootstrap
      - run:
          name: testrpc
          command: npm run testrpc -- --db testrpc_snapshot
          background: true
      - run: yarn lerna:run test:circleci
      - run: if [ $CIRCLE_BRANCH = "development" ]; then yarn lerna:run test:umd; fi
      - run: yarn lerna:run lint
